### PR TITLE
fix : Removed OpenTelemetry.Exporter.Jaeger

### PR DESCRIPTION
**Pull request by gantanikhilraj**
Removed OpenTelemetry.Exporter.Jaeger package 
closes issue #56

### CODE REVIEW

**Comment by JobaDiniz** [comment]
The build has failed. You need to remove the code that uses that package

**Review by JobaDiniz — COMMENTED** [review]
image

**Comment by gantanikhilraj** [comment]
@JobaDiniz , can you help me with, how to sign the commits.

**Comment by JobaDiniz** [comment]
Try to follow this https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Pull request closed without merging**
